{{- if .Values.adotCollector.daemonSet.enabled }}
# ConfigMap for ADOT Collector as a DaemonSet with the specified configurations, including configured values from values.yaml.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.adotCollector.daemonSet.configMap.name }}
  namespace: {{ .Values.adotCollector.daemonSet.namespace }}
  labels:
    app: {{ .Values.adotCollector.daemonSet.configMap.app }}
    component: {{ .Values.adotCollector.daemonSet.configMap.component }}
    {{- include "adotCollector.daemonSet.labels" . | indent 4 }}
data:
  adot-config:  |
    extensions:
      health_check: {{ .Values.adotCollector.daemonSet.extensions.healthCheck }}
      sigv4auth:
        region: {{ .Values.awsRegion }}
    receivers:
      otlp:
        protocols: 
          grpc:
            endpoint: {{ .Values.adotCollector.daemonSet.otlpreceivers.grpcendpoint }}
          http:
            endpoint: {{ .Values.adotCollector.daemonSet.otlpreceivers.httpendpoint }}
    processors:
      batch/traces:
        timeout: {{ .Values.adotCollector.daemonSet.processors.timeout }}
        send_batch_size: {{ .Values.adotCollector.daemonSet.processors.batch_size }}
    exporters:
      otlp/2:
        endpoint: {{ .Values.adotCollector.daemonSet.data_prepper_svc }}
      tls: 
        insecure: {{ .Values.adotCollector.daemonSet.tls_setting_insecure | default "true" }}
    service:
      telemetry:
        logs:
          level: {{ .Values.adotCollector.daemonSet.log_level | default "info" }}
      pipelines:
        traces: 
          receivers: {{- range .Values.adotCollector.daemonSet.service.traces.receivers }}
          - {{.}} {{- end }}
          exporters: {{- range .Values.adotCollector.daemonSet.service.traces.receivers }}
          - {{.}} {{- end }}
      extensions: {{- range .Values.adotCollector.daemonSet.service.extensions }}
      - {{.}} {{- end }}
{{- end }}
