apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
  namespace: opentelemetry-operator-system
spec:
  ports:
  - name: grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  selector:
    app.kubernetes.io/component: opentelemetry
